services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch_snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - rag-net

  rag-api:
    build: .
    image: dguilliams3/rag-api:latest
    container_name: rag_api
    env_file:
      - .env
    environment:
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GPT_MODEL: ${GPT_MODEL}
      GPT_SERVICE_URL: http://gpt-service:8001
    ports:
      - "5000:5000"
    volumes:
      - ./indexes:/app/indexes
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - elasticsearch
    networks:
      - rag-net

  gpt-service:
    build:
      context: .
      dockerfile: Dockerfile.gpt_service
    image: dguilliams3/gpt-service:latest
    container_name: gpt_service
    env_file:
      - .env
    environment:
      GPT_SERVICE_URL: http://localhost:8001/generate
    ports:
      - "8001:8001"

volumes:
  es_data:

networks:
  rag-net:
    driver: bridge
