services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch_snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - rag-net

  rag-api:
    build: .
    image: dguilliams3/rag-api:latest
    container_name: rag_api
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GPT_MODEL=${GPT_MODEL}
    ports:
      - "5000:5000"
    volumes:
      - ./indexes:/app/indexes
      - ./data:/app/data
    depends_on:
      - elasticsearch
    networks:
      - rag-net

volumes:
  es_data:

networks:
  rag-net:
    driver: bridge
